### ISSUE TITLE
Setting hostname via config.txt doesn't share this with DHCP server

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-rootfs#16]
At DLS we get everything from DHCP server, including hostname, via the following mechanism:
- Setup DHCP server with hostname, MAC address, NTP servers, etc
- At DHCP time on PandA, use a udhcp `default.script` to try and get hostname from IP address in Python
Inspired by: https://askubuntu.com/questions/104918/how-to-get-the-hostname-from-a-dhcp-server

A user would like to set the hostname on the PandA, then get the PandA to share this with the DHCP server:

> Under RHEL the hostname can be sent by using the option “DHCP_HOSTNAME=xyz” for example.

A quick glance at udhcp's man pages doesn't seem to have this option:
https://udhcp.busybox.net/README.udhcpc

**Comment by thomascobb** [comment]
Any ideas @Araneidae ?

**Comment by Araneidae** [comment]
I guess we have two options:

1. Patch the required functionality into udhcpc and push our changes upstream if possible; or
2. Find and deploy a more fully functional DHCP client instead of udhcpc.

A quick search leads me to the [ArchWiki dhcpcd page](https://wiki.archlinux.org/index.php/Dhcpcd) and the [dhcpcd home page](https://roy.marples.name/projects/dhcpcd/).  It would require some effort on our part to integrate and configure this correctly, and we'd need to verify that this is the most appropriate DHCP client to use.

**Comment by thomascobb** [comment]
There might be a way:
```
root@TS-MO-PANDA-01:~# udhcpc --help
udhcpc: option requires an argument -- 'h'
BusyBox v1.23.2 (2020-08-05 14:14:03 BST) multi-call binary.

Usage: udhcpc [-fbqRB] [-a[MSEC]] [-t N] [-T SEC] [-A SEC/-n]
        [-i IFACE] [-s PROG] [-p PIDFILE]
        [-oC] [-r IP] [-V VENDOR] [-F NAME] [-x OPT:VAL]... [-O OPT]...

...
        -x OPT:VAL              Include option OPT in sent packets (cumulative)
                                Examples of string, numeric, and hex byte opts:
                                -x hostname:bbox - option 12
...
```
Any idea what calls udhcpc?

**Comment by thomascobb** [comment]
Ah, I see the defilintion of `udhcpc_opts` in `/etc/init.d/parse-config`. I guess we can try putting some `-x` options in there?

**Comment by Araneidae** [comment]
Also have a look at the `default.script` and `zcip.script` files which are installed in `/usr/share/udhcpc` by `rootfs/network/file-list` in the build.
